modbus:
    modbus_type: tcp
    method: rtu
    port: /dev/ttyS4
    stopbits: 1
    bytesize: 8
    parity: E
    baudrate: 19200
    ip: 127.0.0.1
    OFFSET_REGISTERS: 1
    UNIT_ID: 0x1
    byte_order: big
    word_order: little
    registers: {signal_strength:[200,32int],flow_rate:[202,32int],net_total:[204,32int],positive_totalizer:[206,32int],negative_totalizer:[208,32int]}
    #registers: {signal_strength:[200,32int],flow_rate:[202,32int],net_total:[204,32int],positive_totalizer:[206,32int],negative_totalizer:[208,32int],temp1:[210,32int]}
