modbus:
    modbus_type: tcp
    method: rtu
    port: /dev/ttyS4
    stopbits: 1
    bytesize: 8
    parity: E
    baudrate: 19200
    ip: 127.0.0.1
    OFFSET_REGISTERS: 0
    UNIT_ID: 0x1
    byte_order: big
    word_order: little
    registers: {signal_strength:[200,32int],flow_rate:[202,32int],net_total:[204,32int],positive_totalizer:[206,32int],negative_totalizer:[208,32int]}
    #registers: {signal_strength:[200,32int],flow_rate:[202,32int],net_total:[204,32int],positive_totalizer:[206,32int],negative_totalizer:[208,32int],temp1:[210,32int]}

local_database_config:
    host: localhost
    database: local_btu
    protocol: json
    port: 8086
    use_ssl: False
    verify_ssl_is_on: False
    measurement_name: btu_meters
    username: admin
    password: password
    tags: sensor_id,ip
    sensor_id: meter1
    tag_dict: {sensor_id: meter1,ip: 127.0.0.1}
    tag_list: [sensor_id, ip]
    tag_values: [meter1, 127.0.0.1]
    fields: [signal_strength, flow_rate, net_total, positive_totalizer, negative_totalizer]


remote_database_config:
    host: localhost
    database: remote_btu
    protocol: json
    port: 8086
    use_ssl: False
    verify_ssl_is_on: False
    measurement_name: btu_meters
    username: admin
    password: password
    tags: sensor_id,ip
    sensor_id: meter1
    tag_dict: {sensor_id: meter1,ip: 127.0.0.1}
    tag_list: [sensor_id, ip]
    tag_values: [meter1, 127.0.0.1]
    fields: [signal_strength, flow_rate, net_total, positive_totalizer, negative_totalizer]
